# This file is intended to specify custom values.
# Provide as an argument to ytt using arg --data-values-file
# e.g. ytt --data-values-file values-overrides.yaml -f <YAML files>

# Namespaces in which to set up access control for
# supply chains, workloads, deliveries, and deliverables
# Namespaces must be created manually first
namespaces:
  - name: default
  - name: apps-dev
  - name: apps-prod

##################################################
##### git configuration
##### --> create .ssh/id_rsa and .ssh/known_hosts
#####     colocated with ytt processing files
##################################################
# Git repository
git:
  server: github.com
  # Copy your private key file to setup/access-control/.ssh/id_rsa
  # Copy your known_hosts file to setup/access-control/.ssh/known_hosts

##################################################
##### image registry configuration
##################################################
registry:
  server: https://index.docker.io/v1/
  username: ciberkleid
  # Use a personal access token as the password
  password:
  tagPrefix: docker.io/ciberkleid/cartographer-demo-

## GCP settings:
#registry:
#  server: https://us-east4-docker.pkg.dev
#  username: _json_key
#  # Username must be "_json_key".
#  # Copy your key file to setup/access-control/.ssh/gcp-service-account.json
#  tagPrefix: us-east4-docker.pkg.dev/fe-ciberkleid/cartographer-demo/

## The image prefix must be manually set in the
## setup and workflow files
# e.g. index.docker.io/ciberkleid/cartographer-demo-
# e.g. us-east4-docker.pkg.dev/fe-ciberkleid/cartographer-demo/
# If it is changed, reinstall setup/access-control and setup/kpack

##################################################
##### vendir configuration
##################################################

# Vendir configuration
vendir:
  # getLatest overrides declared versions
  # Enable using getLatest: "true" and disable using getLatest: ""
  getLatest: ""
  versions:
    cert-manager: 1.6.1
    secretgen-controller: 0.7.1
    cartographer: 0.1.0
    flux2: 0.24.1
    kpack: 0.5.0
    tekton: 0.31.0
    kapp-ctrl: 0.30.0
    knative: 1.1.0