#@ load("@ytt:data", "data")
#@ load("@ytt:json", "json")

---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
stringData:
  #@ registry_creds = {"username": data.values.registry.username, "password": data.values.registry.password}
  .dockerconfigjson: #@ json.encode({"auths": {data.values.registry.server: registry_creds}})