#@ load("@ytt:data", "data")

---
apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: store
spec:
  sources:
    - image: gcr.io/paketo-buildpacks/go
    - image: gcr.io/paketo-buildpacks/java
    - image: gcr.io/paketo-buildpacks/nodejs
---
apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: stack
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: "paketobuildpacks/build:base-cnb"
  runImage:
    image: "paketobuildpacks/run:base-cnb"
---
apiVersion: kpack.io/v1alpha1
kind: ClusterBuilder
metadata:
  name: builder
spec:
  serviceAccountRef:
    name: service-account
    namespace: default
  tag: #@ data.values.image_prefix + "builder"
  stack:
    name: stack
    kind: ClusterStack
  store:
    name: store
    kind: ClusterStore
  order:
    - group:
        - id: paketo-buildpacks/go
    - group:
        - id: paketo-buildpacks/java
    - group:
        - id: paketo-buildpacks/nodejs