apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-k8s
  labels:
    app.tanzu.vmware.com/workload-type: web-image
spec:
  image: paulbouwer/hello-kubernetes
  env:
    - name: PORT
      value: "8080"
    - name: MESSAGE
      value: "Hello, sunshine!"
    - name: KUBERNETES_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: KUBERNETES_POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: KUBERNETES_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName


