#@ load("@ytt:data", "data")

#@ for i in range(len(data.values.namespaces)):
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
  namespace: #@ data.values.namespaces[i].name
secrets:
  - name: registry-credentials
  - name: git-credentials
imagePullSecrets:
  - name: registry-credentials
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kapp-permissions
  namespace: #@ data.values.namespaces[i].name
rules:
  - apiGroups:
      - serving.knative.dev
    resources: ['services']
    verbs: ['*']
  - apiGroups: [""]
    resources: ['configmaps']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kapp-permissions
  namespace: #@ data.values.namespaces[i].name
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kapp-permissions
subjects:
  - kind: ServiceAccount
    name: service-account
#@ end