apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  labels:
    # This label should match the desired ClusterSupplyChain's selector
    apps.tanzu.vmware.com/workload-type: web2pkg
  name: hello-go-web2pkg
spec:
  serviceAccountName: workload-service-account
  source:
    git:
      url: https://github.com/ciberkleid/go-sample-app.git
      ref:
        branch: master
  env:
    - name: NAME
      value: "Cartographer pkgops ninja 1"
  params:
    - name: containerPort
      value: 8080
    - name: language
      value: golang