apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello-nodejs
  labels:
    app.tanzu.vmware.com/workload-type: web
spec:
  source:
    git:
      url: https://github.com/making/hello-nodejs
      ref:
        branch: master