#@ load("@ytt:data", "data")

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
#@ if data.values.registry.password != "":
secrets:
  - name: registry-credentials
imagePullSecrets:
  - name: registry-credentials
#@ end