apiVersion: carto.run/v1alpha1
kind: ClusterImageTemplate
metadata:
  name: workload-kpack-image
spec:
  imagePath: .status.latestImage
  template:
    apiVersion: kpack.io/v1alpha1
    kind: Image
    metadata:
      name: $(workload.metadata.name)$
      labels:
        app.kubernetes.io/part-of: $(workload.metadata.name)$
    spec:
      tag: $(params.tagPrefix)$$(workload.metadata.name)$
      serviceAccount: service-account
      builder:
        kind: ClusterBuilder
        name: builder
      source:
        blob:
          url: $(source.url)$
      build: #! Optional
        env:
          - name: BP_OCI_SOURCE
            value: $(workload.spec.source.git.url)$
          - name: BP_OCI_REVISION
            value: $(source.revision)$