apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: app-deploy-service
spec:
  params:
    - name: containerPort
      default: 8080
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: $(workload.metadata.name)$
      labels:
        app.kubernetes.io/part-of: $(workload.metadata.name)$
    spec:
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: $(params.containerPort)$
      selector:
        app.kubernetes.io/part-of: $(workload.metadata.name)$
      type: ClusterIP